#
# Copyright The NOMAD Authors.
#
# This file is part of NOMAD. See https://nomad-lab.eu for further info.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

from nomad.datamodel.metainfo.eln import Process
from nomad.parsing.tabular import TableData
from nomad.datamodel.metainfo.eln import Sample
from nomad.datamodel.metainfo.eln import Instrument
from nomad.datamodel.metainfo.eln import Chemical
import numpy as np
from nomad.metainfo import MEnum, Package, Quantity, Section, SubSection
from nomad.datamodel.data import EntryData

m_package = Package(name='Electronic Lab Notebook example schema')


class MyChemical(Chemical, EntryData):
    '''This is an example description for Chemical.
A description can contain **markdown** markup and TeX formulas, like $\\sum\\limits_{i=0}^{n}$.'''
    m_def = Section(label="Instrument")
    form = Quantity(type=MEnum(['crystalline solid', 'powder']), )

    cas_number = Quantity(type=str, )

    ec_number = Quantity(type=str, )


class MyInstrument(Instrument, EntryData):
    '''Class autogenerated from yaml schema.'''
    m_def = Section(label="Instrument")


class MyProcess(Process):
    '''Class autogenerated from yaml schema.'''
    m_def = Section(label="Process")
    instrument = Quantity(type=MyInstrument, )


class PvdEvaporation(MyProcess, TableData):
    '''Class autogenerated from yaml schema.'''
    m_def = Section(
        a_eln={
            "overview": True, "hide": [
                "name", "lab_id", "description", "method"]}, a_plot={
            "title": "Pressure and Temperature over Time", "x": "time", "y": [
                "chamber_pressure", "substrate_temperature"]})
    data_file = Quantity(
        type=str,
        description='A reference to an uploaded .csv produced by the PVD evaporation instruments\ncontrol software.\n',
    )

    time = Quantity(type=np.float64, shape=['*'], unit='s', )

    chamber_pressure = Quantity(type=np.float64, shape=['*'], unit='mbar', )

    substrate_temperature = Quantity(
        type=np.float64, shape=['*'], unit='kelvin', )


class HotplateAnnealing(MyProcess):
    '''Class autogenerated from yaml schema.'''
    m_def = Section(
        a_eln={
            "overview": True,
            "hide": [
                "name",
                "lab_id",
                "description"]})
    set_temperature = Quantity(type=np.float64, unit='K', )

    duration = Quantity(type=np.float64, unit='s', )


class Processes:
    '''Class autogenerated from yaml schema.'''
    m_def = Section(a_eln=None)
    pvd_evaporation = SubSection(section_def=PvdEvaporation)
    hotplate_annealing = SubSection(section_def=HotplateAnnealing)


class MySample(Sample, EntryData):
    '''Class autogenerated from yaml schema.'''
    m_def = Section(
        a_template={
            "processes": {
                "pvd_evaporation": {}}},
        label="Sample")
    name = Quantity(type=str, )

    tags = Quantity(type=MEnum(
        ['internal', 'collaboration', 'project', 'other']), shape=['*'], )

    chemicals = Quantity(type=MyChemical, shape=['*'], )

    substrate_type = Quantity(type=MEnum(
        ['Fused quartz glass', 'SLG', 'other']), )

    substrate_thickness = Quantity(type=np.float64, unit='m', )

    sample_is_from_collaboration = Quantity(type=bool, )

    processes = SubSection(section_def=Processes)


m_package.__init_metainfo__()
